[build]
  command = "" # Leave this empty if you're not building frontend assets
  functions = "functions" # Path to your serverless functions directory
  publish = "API" # Set the publish directory to the root directory (API)


  
[dev]
  command = "node api_server.js" # Command to start your Express.js server locally